language: c
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    # @TODO: below seems to prompt to overwrite sshkey
    # unclear why this does this on this version
    # - os: osx
    #   osx_image: xcode9.2
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
      sudo: required
install: ./build.sh
before_script:
  - sudo apt-get purge --auto-remove nodejs || true
  - sudo rm -f $(which node) || true
  - ./bin/hyperdrive --version
script:
  - ./bin/hyperdrive -y --name="Obi-Wan Kenobi" --email hermit@tatooine.org --vim
  - # @TODO: Ideally we should get Leia in here for the tests but lets slum it for now
  - # Print out and see if we are up to date
  - # this may produce unexpected results for docker on macOS
  - ./bin/hyperdrive -y --name="Obi-Wan Kenobi" --email hermit@tatooine.org --vim
deploy:
  provider: releases
  api_key:
    secure: DGdNfOYuDii+WuEzZeyH5hkJVPXttOrmLEW0gCPqr0XUpW92g4jBJyzg+40O8Qu9W8qcbnfuT/nD1ewtzTYlgpJIjwRwLYK5tLDdXOrcwCIHbdmpVd0B3+581SUBZBfBSLSI5Kn+6bemb660ZcunX2xbuDYhbmcQeWfo80St14GzWOYg8vNgPiQwd92eXuZBgl9wyeOEX240zFofAKCmRnNi/q84i/wT5FpImGZJk6aibrkP5s+nqMkU3sH9g+angB3Wnrohjb3oXSw6TTpyayKe+0d1yxLCOBoMzYPU7cpzp+m6iBtu50UtdwjlZa6wLrL4kKcd/+hYjQqxCg8z6w7R5TGCDP+KS/KKGmCXmPWmQQbPjXT4EtQdvQGXAhxVIZLAff6rmEMLqS+D8JxHiEBjTn5sL7k2XbOWGkO0tHKlQb0djDZNJ5OPy7TVtAMRLkStguAolLp3kFcb1ukZokFnLDAXkxIYu77cp480fWEWnXDJ6mxDpcMqtPeBb8MoEdAjlCk7TcW9k86deY93RvhlO02y0u9wg7PHpjp2h3mh2nCa1aexBX3hUtnxRjx5BL3E/WLoM62orCwqmfl1d9DXciFVoolpOOVwIuBiPYoaL0DnPgDL+NiDwPxbSz5/9acwz1hVluLTeVn6+kYiht9dldYGg9LgUIGKd0BWjZg=
  file: ./bin/hyperdrive
  skip_cleanup: true
  on:
    repo: lando/hyperdrive
    tags: true
