language: c
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    # @TODO: below seems to prompt to overwrite sshkey
    # unclear why this does this on this version
    # - os: osx
    #   osx_image: xcode9.2
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
      sudo: required
install: ./build.sh
before_script:
  - sudo apt-get purge --auto-remove nodejs || true
  - sudo rm -f $(which node) || true
  - ./bin/hyperdrive --version
script:
  - ./hyperdrive.sh -y --name="Obi-Wan Kenobi" --email hermit@tatooine.org --vim
  - # @TODO: Ideally we should get Leia in here for the tests but lets slum it for now
  - # Print out and see if we are up to date
  - # this may produce unexpected results for docker on macOS
  - ./bin/hyperdrive -y --name="Obi-Wan Kenobi" --email hermit@tatooine.org --vim
deploy:
  provider: releases
  api_key:
    secure: dExeDy5NPX7YAD1oKjGvscToiFTosKzqYQRkSq4zf0NKirWr/Vkt+Ke20hwMT4PXcdCxpWzPxeAUzMWzNh4ExqvD1797yI046K32e6F6ayZlYbyYct25Quj7E3OKDMac5sPUT7MOGZ0RD13vuDZUVL9c5v/rmyAhdoYcJw+LJNKq83I/pI2+5Wz9saISVgcPzGVRvh/knJRFbdJdPpwzNySf7hvIA7V8f3V2nlXO6QAgBV/wlYZ/lbwpvH6TeXAGC9cUZgTjQ0FblBha3s+34mJh7oFVtd/gFkOmdVt4jrN5EwGvaQYlpHBDDKDZzbLWrIbZisSgBx+AauJyoxa8LKlE9F8gk3oLr9ZBjX/aQ7K1J8EDw3RbYSJRIb1EuOivhwdL8/3tijzbxLG9aLeA5pL6iR5M6GPMz3luRHTzv+IBRV39poDWbnVCSD+Qp+vEPKk+9YP8X+0BBF78FPyd1UIQyiRpJ9AqL4kEhf7SZy6byBNFkMP2orSsCKtKiJQMbmVUm2khsWnWMZxcgBTgWUEaY4ZcIWxzBLRV8TJt9bTuwNtN8cP9M1SUbcDyFqgL2guZ24FEDgOCWdRq/376dpNgrSc/n5T4hr2v+NzMvUA94XFda/CBpRaESWpV5kE2OqNGp4yn7xTzboVgZjcW73gVBqlauEcRqRPLmyb56yI=
  file: ./bin/hyperdrive
  skip_cleanup: true
  on:
    repo: lando/hyperdrive
    tags: true
