deps:
  packages:
    docker-compose:
      versions:
        default: 1.29.2
        preferred: ">=1.29.x && <2.x"
        required: ">=1.x && <2.x"
    docker-desktop:
      versions:
        default: 4.10.1
        preferred: ">=4.x && <5.x"
        required: ">=3.x && <5.x"
    lando:
      versions:
        default: 4.0.0-alpha.1
        preferred: ">=4.x"
        required: ">=4.x"
      requires:
        docker-desktop: true
        docker-compose: true
npm:
plugins:
updates:
  notify: true
core:
  telemetry: true
  release-channel: stable
